### ISSUE TITLE
how does multi-stream use this connector?

### ISSUE THREAD

**Issue by jorgen-zhao** [Chrisss93/flink-connector-nats#6]
Hi there, firstly, I'm not sure if you are currently maintaining this project. I have a question and I'm hoping you can assist me.

In the README, it states that the source connector is designed to consume from a **single** NATS stream using one or more NATS consumers. However, I need to handle multiple Jetstreams now. Currently, I am using the **dataSource union** method to address this problem. However, when I increase the number of Jetstreams to around 30 or more, the solution no longer works.

Considering this issue, I would like to ask for your help. Do you have any ideas or suggestions on how to tackle this problem?

Any assistance you can provide would be greatly appreciated. Thank you in advance.

**Comment by Chrisss93** [comment]
Hello.  The reason to limit a source connector to consume from a single NATS stream is because *generally* in my experience most messages within a single stream have the same underlying structure, meaning the user can configure the source connector to deserialize messages into a more meaningful and helpful data structure.  To consume messages from N NATS streams into a single Flink, I would indeed make N instances of the source connector targeting each individual NATS stream and use Flink's DataStream UNION API to merge them into a single DataStream.  Can you be more specific when you say: >30 JetStream source connectors no longer works? What about it doesn't work?

This is more on the ops side but I would also suggest, if you are needing to union 30 JetStreams inside a Flink job, I would assume all those JetStreams messages might have the same structure?  In that case, you might consider creating a single NATS JetStream (outside of Flink jobs) which is simply a union of all the subjects targeted by the individual 30 JetStreams.  Then you would need only a single source connector, generating a single NATS consumer on a single JetStream.
